### ISSUE TITLE
Scheduling von Artikeln nicht möglich

### ISSUE THREAD

**Issue by Le1b1** [cccs/cccs-website#95]
Wäre hilfreich, wenn Artikel erst veröffentlicht werden, sobald 'created_at' erreicht wurde.

**Comment by Skyr** [comment]
Warum? Im git sind sie ab dem Push sichtbar.
Desweiteren erschwert es eine Menge Dinge: Wenn man sie vor dem Datum aus der Nodeliste herauslässt, hat man mit einem Mal eine Menge potentielle Schwierigkeiten bei Übersichtslisten, zum Artikel gehörigen Bildern, etc.

**Comment by Le1b1** [comment]
Ok, das sind gute Argumente.
Hätte bei den PMs geholfen, schon alles vor bereiten zu können und dann ohne aktives Zutun zu veröffentlichen, aber den Aufwand scheint es nicht wert.
